# Generated by Django 4.2.24 on 2025-10-02 00:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0005_remove_flexiblepage_advancedflexiblepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_sections',
            field=wagtail.fields.StreamField([('stats_section', 5), ('links_section', 12), ('content_boxes', 18), ('project_highlights', 25), ('news_section', 30), ('custom_html', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g., '500+', '$10M'"}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g., 'Users', 'Funding'"}), 3: ('wagtail.blocks.StructBlock', [[('number', 1), ('label', 2), ('description', 0)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('stats', 4)]], {'icon': 'snippet'}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.URLBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon class or emoji', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('url', 7), ('description', 8), ('icon', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 11)]], {'icon': 'link'}), 13: ('wagtail.blocks.RichTextBlock', (), {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 6), ('content', 13), ('image', 14), ('link_text', 0), ('link_url', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 0), ('boxes', 17)]], {'icon': 'grid'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Project Highlights'}), 20: ('wagtail.blocks.TextBlock', (), {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More'}), 22: ('wagtail.blocks.ListBlock', (6,), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 20), ('image', 14), ('link_url', 15), ('link_text', 21), ('tags', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('section_title', 19), ('projects', 24)]], {'icon': 'doc-full'}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Latest News'}), 27: ('wagtail.blocks.DateBlock', (), {}), 28: ('wagtail.blocks.StructBlock', [[('title', 6), ('date', 27), ('summary', 20), ('image', 14), ('link_url', 15), ('category', 0)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('section_title', 26), ('news_items', 29)]], {'icon': 'date'}), 31: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, help_text='Call to action button link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, help_text='Call to action button text', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
