# Generated by Django 4.2.24 on 2025-10-01 21:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'General', 'Billing', 'Technical Support'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name for this FAQ collection (e.g., 'Homepage FAQs', 'Product FAQs')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of this collection')),
            ],
            options={
                'verbose_name': 'FAQ Collection',
                'verbose_name_plural': 'FAQ Collections',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question being asked', max_length=500)),
                ('answer', wagtail.fields.RichTextField(help_text='The answer to the question (supports rich text)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this FAQ (e.g., show on homepage)')),
                ('is_published', models.BooleanField(default=True, help_text='Show this FAQ on the website')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the question (optional)', max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Categorize this FAQ item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='faq.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['category', 'display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FAQCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('collection', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='faq.faqcollection')),
                ('faq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='faq.faqitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
