# Generated by Django 4.2.24 on 2025-10-01 17:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedFlexiblePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('html', 7), ('quote', 9), ('button', 13), ('embed', 14), ('two_columns', 17), ('call_to_action', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4'), ('h5', 'Heading 5'), ('h6', 'Heading 6')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {'icon': 'title'}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt_text', 5)]], {'icon': 'image'}), 7: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('quote', 8), ('author', 5)]], {'icon': 'openquote'}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 13: ('wagtail.blocks.StructBlock', [[('text', 10), ('url', 11), ('style', 12)]], {'icon': 'link'}), 14: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 15: ('wagtail.blocks.RichTextBlock', (), {}), 16: ('wagtail.blocks.StreamBlock', [[('paragraph', 15), ('image', 4)]], {}), 17: ('wagtail.blocks.StructBlock', [[('left_column', 16), ('right_column', 16)]], {'icon': 'columns'}), 18: ('wagtail.blocks.StructBlock', [[('title', 10), ('text', 15), ('button_text', 10), ('button_url', 11)]], {'icon': 'warning'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FlexiblePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('html', 3), ('quote', 4), ('embed', 5), ('list', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ul'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
