# Generated by Django 4.2.24 on 2025-10-03 00:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedflexiblepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('html', 7), ('quote', 9), ('button', 13), ('embed', 14), ('two_columns', 17), ('call_to_action', 18), ('list_with_links', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4'), ('h5', 'Heading 5'), ('h6', 'Heading 6')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {'icon': 'title'}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt_text', 5)]], {'icon': 'image'}), 7: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('quote', 8), ('author', 5)]], {'icon': 'openquote'}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')]}), 13: ('wagtail.blocks.StructBlock', [[('text', 10), ('url', 11), ('style', 12)]], {'icon': 'link'}), 14: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 15: ('wagtail.blocks.RichTextBlock', (), {}), 16: ('wagtail.blocks.StreamBlock', [[('paragraph', 15), ('image', 4)]], {}), 17: ('wagtail.blocks.StructBlock', [[('left_column', 16), ('right_column', 16)]], {'icon': 'columns'}), 18: ('wagtail.blocks.StructBlock', [[('title', 10), ('text', 15), ('button_text', 10), ('button_url', 11)]], {'icon': 'warning'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the list', 'required': False}), 20: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 10), ('link', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('items', 22)]], {'icon': 'list-ul'})}),
        ),
    ]
