# Generated by Django 4.2.24 on 2025-10-03 00:11

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_advancedflexiblepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('html', 3), ('quote', 4), ('embed', 5), ('list', 7), ('list_with_links', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ul'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the list', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 6), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('items', 11)]], {'icon': 'list-ul'})}),
        ),
    ]
