# Generated by Django 4.2.25 on 2025-10-07 22:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Project subtitle or tagline', max_length=255)),
                ('principal_investigator', models.CharField(blank=True, help_text='Name of the principal investigator', max_length=255)),
                ('institution', models.CharField(blank=True, help_text='Institution or organization', max_length=255)),
                ('project_info', wagtail.fields.RichTextField(blank=True, help_text='General project information')),
                ('abstract', wagtail.fields.RichTextField(blank=True, help_text='Project abstract or summary')),
                ('references', wagtail.fields.RichTextField(blank=True, help_text='Project references and citations')),
                ('github_repo_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('jupyter_lab_url', models.URLField(blank=True, help_text='JupyterLab server URL')),
                ('jupyter_cta_text', models.CharField(default='Launch JupyterLab', help_text='Call to action button text', max_length=100)),
                ('project_image', models.ForeignKey(blank=True, help_text='Main project image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
