# Generated by Django 4.2.25 on 2025-10-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxprojectpage',
            name='hosting_platform',
            field=models.CharField(blank=True, choices=[('jetstream2', 'JetStream2'), ('huggingface', 'Hugging Face'), ('national_data_platform', 'National Data Platform'), ('other', 'Other')], help_text='Platform where the project is hosted', max_length=50),
        ),
        migrations.AddField(
            model_name='sandboxprojectpage',
            name='principal_investigator_image',
            field=models.ForeignKey(blank=True, help_text='Principal investigator photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sandboxprojectpage',
            name='principal_investigator_url',
            field=models.URLField(blank=True, help_text='Principal investigator website or profile URL'),
        ),
        migrations.AddField(
            model_name='sandboxprojectpage',
            name='project_type',
            field=models.CharField(choices=[('classroom', 'Classroom'), ('pilot', 'Pilot'), ('startup', 'Startup')], default='pilot', help_text='Type of project', max_length=20),
        ),
    ]
