# Generated by Django 4.2.24 on 2025-10-01 18:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('menu_items', wagtail.fields.StreamField([('menu_item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('link_url', 2), ('description', 4), ('open_in_new_tab', 3)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('link_url', 2), ('open_in_new_tab', 3), ('sub_items', 6)]], {})})),
            ],
            options={
                'verbose_name': 'Mega Menu',
                'verbose_name_plural': 'Mega Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to an internal page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, help_text='Optional short description', max_length=255)),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to an internal page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('parent_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='navigation.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='navigation.navigationmenu'),
        ),
    ]
