# Generated by Django 4.2.24 on 2025-10-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='navigationmenu',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Navigation Menu', 'verbose_name_plural': 'Navigation Menus'},
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first in the list'),
        ),
    ]
