# Generated by Django 4.2.24 on 2025-10-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('navigation', '0002_alter_menuitem_options_alter_navigationmenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this menu directly to a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional: Or link to an external URL'),
        ),
    ]
