# Generated by Django 4.2.24 on 2025-10-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_navigationmenu_link_page_navigationmenu_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Or link to a URL (can be relative like /about or full URL)', max_length=500),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='link_url',
            field=models.CharField(blank=True, help_text='Optional: Or link to a URL (can be relative like /about or full URL)', max_length=500),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Or link to a URL (can be relative like /about or full URL)', max_length=500),
        ),
    ]
