# Generated by Django 4.2.24 on 2025-10-01 21:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Engineering', 'Marketing', 'Sales'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Software Engineer', 'Marketing Manager', 'CEO'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this role')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, help_text='Leave blank to auto-generate from first and last name', max_length=255)),
                ('bio', wagtail.fields.RichTextField(blank=True, help_text='Team member biography')),
                ('short_bio', models.CharField(blank=True, help_text='Short bio for card displays', max_length=255)),
                ('custom_title', models.CharField(blank=True, help_text='Custom job title (overrides role if provided)', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_author', models.BooleanField(default=False, help_text='Can this person author blog posts or articles?')),
                ('author_slug', models.SlugField(blank=True, help_text='URL-friendly name for author pages', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this member on team pages')),
                ('is_active', models.BooleanField(default=True, help_text='Is this person currently with the organization?')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('joined_date', models.DateField(blank=True, help_text='When they joined the organization', null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='team.department')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='team.role')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('github', 'GitHub'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Personal Website'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('custom_label', models.CharField(blank=True, help_text='Optional custom label', max_length=100)),
                ('team_member', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='team.teammember')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="e.g., 'Python', 'Project Management', 'UX Design'", max_length=100)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
                ('team_member', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_areas', to='team.teammember')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
