# Generated by Django 4.2.25 on 2025-10-06 23:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal name for this footer (e.g., 'Main Footer')", max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short company tagline or description', max_length=255)),
                ('description', models.TextField(blank=True, help_text='About the company (short paragraph)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('copyright_text', models.CharField(blank=True, help_text="e.g., '© 2025 Company Name. All rights reserved.'", max_length=255)),
                ('content_sections', wagtail.fields.StreamField([('text_section', 2), ('link_list', 8), ('image_section', 11), ('contact_info', 15), ('newsletter_signup', 21), ('custom_html', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {'icon': 'doc-full'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4), ('open_in_new_tab', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 7)]], {'icon': 'list-ul'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 9), ('alt_text', 0), ('caption', 0), ('link', 10)]], {'icon': 'image'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon class or emoji', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('label', 3), ('value', 3), ('icon', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 14)]], {'icon': 'mail'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe to our newsletter'}), 17: ('wagtail.blocks.TextBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Enter your email'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe'}), 20: ('wagtail.blocks.URLBlock', (), {'help_text': 'Form submission URL'}), 21: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 17), ('placeholder', 18), ('button_text', 19), ('action_url', 20)]], {'icon': 'mail'}), 22: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'})})),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text="Column heading (e.g., 'Quick Links', 'Resources')", max_length=100)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_columns', to='footer.footer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('discord', 'Discord'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('other', 'Other')], help_text='Social media platform', max_length=50)),
                ('url', models.URLField(help_text='Full URL to your social media profile')),
                ('custom_label', models.CharField(blank=True, help_text='Optional custom label (defaults to platform name)', max_length=100)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='footer.footer')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Or link to an external URL')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('column', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_links', to='footer.footercolumn')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to an internal page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
