# Generated by Django 4.2.24 on 2025-10-02 18:42

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='content_sections',
            field=wagtail.fields.StreamField([('text_section', 2), ('link_list', 8), ('image_section', 11), ('contact_info', 15), ('newsletter_signup', 21), ('custom_html', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {'icon': 'doc-full'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4), ('open_in_new_tab', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 7)]], {'icon': 'list-ul'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 9), ('alt_text', 0), ('caption', 0), ('link', 10)]], {'icon': 'image'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon class or emoji', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('label', 3), ('value', 3), ('icon', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 14)]], {'icon': 'mail'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe to our newsletter'}), 17: ('wagtail.blocks.TextBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Enter your email'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Subscribe'}), 20: ('wagtail.blocks.URLBlock', (), {'help_text': 'Form submission URL'}), 21: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 17), ('placeholder', 18), ('button_text', 19), ('action_url', 20)]], {'icon': 'mail'}), 22: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code'})}),
        ),
    ]
