# Generated by Django 4.2.25 on 2025-10-08 03:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemonstrationProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_type', models.CharField(choices=[('research', 'Research'), ('education', 'Education'), ('infrastructure', 'Infrastructure'), ('application', 'Application'), ('other', 'Other')], default='research', help_text='Type of demonstration project', max_length=50)),
                ('subtitle', models.CharField(blank=True, help_text='Project subtitle or tagline', max_length=255)),
                ('project_lead_name', models.CharField(blank=True, help_text='Name of the project lead person', max_length=255)),
                ('project_lead_institution', models.CharField(blank=True, help_text='Institution of the project lead', max_length=255)),
                ('project_info', wagtail.fields.RichTextField(blank=True, help_text='General project information and description')),
                ('more_information', wagtail.fields.RichTextField(blank=True, help_text='Additional detailed information about the project')),
                ('project_image', models.ForeignKey(blank=True, help_text='Main project image or banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('project_lead_image', models.ForeignKey(blank=True, help_text='Photo of the project lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Demonstration Project',
                'verbose_name_plural': 'Demonstration Projects',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DemonstrationProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="Team member's full name", max_length=255)),
                ('institution', models.CharField(blank=True, help_text="Team member's institution or organization", max_length=255)),
                ('role', models.CharField(blank=True, help_text="Role or position in the project (e.g., 'Co-Investigator', 'Research Scientist')", max_length=255)),
                ('photo', models.ForeignKey(blank=True, help_text='Team member photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='demonstration_projects.demonstrationprojectpage')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
