# Generated by Django 4.2.25 on 2025-10-08 03:11

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstrationprojectpage',
            name='project_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Brief introduction or overview of the project'),
        ),
    ]
